-- Migración: catálogo legal real y taxonomía funcional para ONG
-- Ejecutar después de database/schema.sql y del seed base.
begin;

insert into subcategories (category_id, name, description, sort_order)
select c.id, x.name, x.description, x.sort_order
from categories c
join (values
  ('Leyes para ONG','Voluntariado','Derechos, deberes y organización de programas de voluntariado.',5),
  ('Leyes para ONG','Protección de datos','Privacidad, consentimiento y seguridad de información.',6)
) as x(category,name,description,sort_order) on x.category=c.name
on conflict (category_id,name) do update set description=excluded.description, sort_order=excluded.sort_order;

-- Sustituye los registros demostrativos anteriores por 30 normas identificables.
delete from knowledge_items
where category_id = (select id from categories where name='Leyes para ONG');

create temporary table legal_catalog (
  title text, description text, content text, subcategory text, author_name text,
  organization text, legal_reference text, source_url text, tags_text text
) on commit drop;

insert into legal_catalog values
('Constitución Política 1993 — Derecho de asociación','Artículo 2, inciso 13 (paráfrasis): toda persona puede asociarse y constituir fundaciones u otras formas de organización jurídica sin fines de lucro, sin autorización previa y conforme a ley. La asociación no puede ser disuelta mediante resolución administrativa.','La base constitucional para crear una ONG como asociación civil es el derecho de asociación. La organización debe actuar con fines lícitos, respetar su estatuto y cumplir las normas aplicables.','Constitución','Ana Administradora','Manos Abiertas','Constitución Política del Perú, artículo 2 inciso 13.','https://www.congreso.gob.pe/Docs/files/constitucion/constitucion-politica-14-03-18.pdf','constitución,asociación,derecho fundamental'),
('Decreto Legislativo N.° 295 — Régimen de asociaciones','Artículo 80 del Código Civil (paráfrasis): la asociación es una organización estable de personas naturales o jurídicas, o de ambas, que mediante una actividad común persigue un fin no lucrativo. Los artículos 81 al 98 desarrollan su estatuto, órganos, libros, acuerdos, disolución y destino patrimonial.','El Código Civil establece las reglas principales de las asociaciones sin fines de lucro: contenido del estatuto, asamblea general, consejo directivo, libros, derechos de asociados, disolución y destino del patrimonio.','Constitución','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 295, Código Civil, artículos 80 al 98.','https://spij.minjus.gob.pe/spij-ext-web/#/detallenorma/H682678','código civil,estatuto,asociación'),
('Ley N.° 27444 — Procedimiento administrativo general','Artículo IV del Título Preliminar (paráfrasis): las autoridades administrativas deben actuar conforme a los principios de legalidad, debido procedimiento, impulso de oficio, razonabilidad, imparcialidad, informalismo y presunción de veracidad durante los trámites de una ONG.','La ONG utiliza esta norma como marco general al realizar procedimientos ante SUNARP, APCI, SUNAT u otras entidades, salvo que exista un procedimiento especial aplicable.','Constitución','Ana Administradora','Manos Abiertas','Ley N.° 27444, Ley del Procedimiento Administrativo General.','https://www.gob.pe/institucion/pcm/normas-legales','trámites,administración pública,procedimiento'),
('Decreto Legislativo N.° 1049 — Función notarial peruana','Artículo 2 (paráfrasis): el notario es el profesional del derecho autorizado para dar fe de los actos y contratos celebrados ante él, formalizar la voluntad de los otorgantes y conservar los instrumentos. Esta función sustenta la escritura pública de constitución de una asociación.','Es relevante para la elevación a escritura pública de la minuta de constitución, certificación de firmas, apertura de libros y otros actos notariales de la asociación.','Constitución','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 1049, Decreto Legislativo del Notariado.','https://www.gob.pe/institucion/minjus/normas-legales','notaría,escritura pública,libros'),
('Ley N.° 26662 — Asuntos no contenciosos','Artículo 1 (paráfrasis): los interesados pueden acudir indistintamente ante el Poder Judicial o ante notario para los asuntos no contenciosos comprendidos por la ley, siempre que no exista controversia que requiera decisión jurisdiccional.','Sirve como referencia complementaria para actuaciones notariales que pueden presentarse durante la vida institucional de una asociación, según el caso concreto.','Constitución','Ana Administradora','Manos Abiertas','Ley N.° 26662, Ley de Competencia Notarial en Asuntos No Contenciosos.','https://www.gob.pe/institucion/minjus/normas-legales','notaría,procedimiento,formalización'),
('Ley N.° 26366 — Sistema registral nacional','Artículo 1 (paráfrasis): se crea el Sistema Nacional de los Registros Públicos para mantener y preservar la unidad y coherencia del ejercicio de la función registral. La ley también crea la SUNARP como organismo rector del sistema registral.','Es la norma institucional que sustenta la organización registral donde se inscriben las asociaciones y sus actos posteriores.','SUNARP','Ana Administradora','Manos Abiertas','Ley N.° 26366, creación del Sistema Nacional de los Registros Públicos y de la SUNARP.','https://www.sunarp.gob.pe/','sunarp,registro público,persona jurídica'),
('Resolución N.° 038-2013-SUNARP/SN — Registro de personas jurídicas','Artículo 1 del Reglamento (paráfrasis): sus disposiciones regulan la inscripción de actos relativos a personas jurídicas en los registros correspondientes. Para las asociaciones comprende constitución, estatuto, órganos de gobierno, poderes, modificaciones y extinción.','Detalla los requisitos registrales para constitución, estatuto, consejos directivos, poderes, modificaciones y demás actos de asociaciones.','SUNARP','Ana Administradora','Manos Abiertas','Resolución del Superintendente Nacional de los Registros Públicos N.° 038-2013-SUNARP/SN.','https://www.sunarp.gob.pe/','sunarp,inscripción,consejo directivo'),
('Resolución N.° 281-2015-SUNARP/SN — Servicio de publicidad registral','Artículo 1 del Reglamento (paráfrasis): la publicidad registral permite que cualquier persona acceda al contenido de las partidas y obtenga certificados, copias o información registral, con las limitaciones establecidas por ley.','Permite solicitar partida registral, vigencia de poder, certificados y otros documentos necesarios para bancos, convenios, convocatorias y trámites.','SUNARP','Ana Administradora','Manos Abiertas','Resolución N.° 281-2015-SUNARP/SN, Reglamento del Servicio de Publicidad Registral.','https://www.sunarp.gob.pe/','publicidad registral,vigencia de poder,certificados'),
('Decreto Legislativo N.° 719 — Cooperación técnica internacional','Artículo 1 (paráfrasis): la cooperación técnica internacional constituye un medio para complementar los esfuerzos nacionales de desarrollo mediante recursos, conocimientos y asistencia provenientes del exterior, sin que ello implique fines de lucro.','Regula la cooperación técnica internacional y sirve de base para los registros y obligaciones de entidades que reciben o ejecutan este tipo de cooperación.','APCI','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 719, Ley de Cooperación Técnica Internacional.','https://www.gob.pe/apci','apci,cooperación internacional,ongd'),
('Decreto Supremo N.° 015-92-PCM — Reglamento de cooperación','Artículo 1 del Reglamento (paráfrasis): se desarrollan las normas y procedimientos para programar, gestionar, ejecutar, seguir y evaluar la cooperación técnica internacional, así como las responsabilidades de las entidades participantes.','Complementa el Decreto Legislativo N.° 719 y orienta sobre la gestión, registro, seguimiento y coordinación de la cooperación técnica internacional.','APCI','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 015-92-PCM, Reglamento del Decreto Legislativo N.° 719.','https://www.gob.pe/apci','apci,reglamento,cooperación'),
('Ley N.° 27692 — Creación de APCI','Artículos 1 y 3 (paráfrasis): se crea la Agencia Peruana de Cooperación Internacional como organismo encargado de conducir, programar, organizar, priorizar y supervisar la cooperación internacional no reembolsable, de acuerdo con la política nacional.','Establece a la APCI como entidad responsable de conducir, programar, organizar, priorizar y supervisar la cooperación internacional no reembolsable.','APCI','Ana Administradora','Manos Abiertas','Ley N.° 27692, Ley de Creación de la APCI.','https://www.gob.pe/apci','apci,creación institucional,supervisión'),
('Ley N.° 28925 — Supervisión de cooperación','Artículo 1 (paráfrasis): se modifican disposiciones de la Ley N.° 27692 para fortalecer el registro, seguimiento, fiscalización y potestad sancionadora de la APCI respecto de entidades que gestionan cooperación internacional no reembolsable.','Es relevante para ONGD que administran cooperación internacional, pues regula aspectos de fiscalización, registros, infracciones y sanciones.','APCI','Ana Administradora','Manos Abiertas','Ley N.° 28925, modificación de la Ley N.° 27692.','https://www.gob.pe/apci','apci,fiscalización,registro ongd'),
('Decreto Supremo N.° 016-2019-RE — Organización de APCI','Artículo 1 (paráfrasis): se aprueba el Reglamento de Organización y Funciones de la APCI, documento que distribuye competencias entre sus órganos y unidades para gestionar registros, fiscalización, cooperación y servicios institucionales.','Permite identificar las unidades responsables, competencias y canales institucionales relacionados con registros, supervisión y servicios de APCI.','APCI','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 016-2019-RE, Reglamento de Organización y Funciones de la APCI.','https://www.gob.pe/apci','apci,organización,funciones'),
('Decreto Legislativo N.° 943 — Registro Único Contribuyentes','Artículo 2 (paráfrasis): deben inscribirse en el RUC quienes sean contribuyentes o responsables de tributos administrados por SUNAT y quienes, aun sin esa condición, requieran identificarse para realizar trámites u operaciones tributarias.','La asociación inscrita debe gestionar su RUC, mantener actualizados sus datos y utilizarlo en sus operaciones y trámites tributarios.','SUNAT','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 943, Ley del Registro Único de Contribuyentes.','https://www.sunat.gob.pe/legislacion/','sunat,ruc,identificación tributaria'),
('Resolución N.° 210-2004/SUNAT — Inscripción y actualización RUC','Artículo 2 (paráfrasis): están obligados a inscribirse en el RUC los sujetos señalados por la normativa tributaria. La resolución regula además los datos, documentos y procedimientos para inscripción, modificación, suspensión y baja.','Orienta la inscripción de la asociación, actualización de domicilio fiscal, representantes legales, actividades económicas y demás información registral tributaria.','SUNAT','Ana Administradora','Manos Abiertas','Resolución de Superintendencia N.° 210-2004/SUNAT y modificatorias.','https://www.sunat.gob.pe/legislacion/superin/2004/210.htm','sunat,ruc,actualización'),
('Decreto Legislativo N.° 774 — Impuesto a la Renta','Artículo 14 (paráfrasis): para efectos del Impuesto a la Renta se consideran personas jurídicas, entre otras, las asociaciones, fundaciones y comités no inscritos cuando corresponda. Su tratamiento tributario depende de la actividad, los ingresos y las condiciones previstas por la ley.','Las asociaciones deben evaluar las condiciones de exoneración, destino de rentas, actividades permitidas, obligaciones formales y tratamiento de ingresos.','SUNAT','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 774, Ley del Impuesto a la Renta.','https://www.sunat.gob.pe/legislacion/renta/','renta,exoneración,tributación'),
('Decreto Supremo N.° 179-2004-EF — Texto único renta','Artículo 19, inciso b), del TUO (paráfrasis): determinadas rentas de asociaciones sin fines de lucro pueden acceder a exoneración cuando su instrumento de constitución comprenda exclusivamente los fines previstos por la norma y cumpla las condiciones legales vigentes.','Es la versión sistematizada de referencia para revisar el tratamiento tributario vigente de asociaciones, donaciones, rentas y exoneraciones.','SUNAT','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 179-2004-EF, TUO de la Ley del Impuesto a la Renta.','https://www.sunat.gob.pe/legislacion/renta/ley/','renta,texto único,exoneración'),
('Decreto Legislativo N.° 821 — Impuesto general ventas','Artículo 1 (paráfrasis): el IGV grava la venta de bienes muebles, la prestación o utilización de servicios, los contratos de construcción, la primera venta de inmuebles realizada por constructores y la importación de bienes.','La ONG debe revisar si las actividades que realiza están gravadas, inafectas o sujetas a reglas especiales, sin asumir que toda operación está exonerada por ser sin fines de lucro.','SUNAT','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 821, Ley del IGV e ISC.','https://www.sunat.gob.pe/legislacion/igv/','igv,operaciones,tributación'),
('Decreto Supremo N.° 055-99-EF — Texto único IGV','Artículo 1 del TUO (paráfrasis): se encuentran gravadas con IGV las operaciones expresamente señaladas por la ley. Una ONG debe evaluar cada operación y no asumir que su condición no lucrativa genera automáticamente inafectación o exoneración.','Es la fuente consolidada para revisar operaciones, comprobantes, crédito fiscal, inafectaciones y demás reglas del IGV aplicables según la actividad de la ONG.','SUNAT','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 055-99-EF, TUO de la Ley del IGV e ISC.','https://www.sunat.gob.pe/legislacion/igv/ley/','igv,texto único,comprobantes'),
('Ley N.° 28238 — Voluntariado nacional peruano','Artículo 2 (paráfrasis): el voluntariado es una labor o actividad realizada sin fines de lucro, en forma gratuita y solidaria, que contribuye al desarrollo del país y se efectúa sin sustituir empleo remunerado.','Es la norma principal para programas de voluntariado. La ONG debe informar funciones, responsabilidades, condiciones de participación, seguridad y reconocimiento del voluntario.','Voluntariado','Ana Administradora','Manos Abiertas','Ley N.° 28238, Ley General del Voluntariado.','https://www.gob.pe/mimp','voluntariado,derechos,deberes'),
('Ley N.° 29094 — Fortalecimiento del voluntariado','Artículo 1 (paráfrasis): se modifican diversos artículos de la Ley General del Voluntariado para fortalecer su promoción, reconocer modalidades de participación y precisar derechos, deberes y responsabilidades de las organizaciones y voluntarios.','Complementa el marco del voluntariado y debe leerse junto con la Ley N.° 28238 y su reglamento.','Voluntariado','Ana Administradora','Manos Abiertas','Ley N.° 29094, modificación de la Ley General del Voluntariado.','https://www.gob.pe/mimp','voluntariado,promoción,participación'),
('Decreto Supremo N.° 003-2015-MIMP — Reglamento del voluntariado','Artículo 1 (paráfrasis): el Reglamento desarrolla la Ley General del Voluntariado y establece disposiciones para organizar, registrar, promover y reconocer la actividad voluntaria, así como para aplicar los derechos y deberes de sus participantes.','Precisa aspectos de organización, registro, derechos, deberes y reconocimiento de la actividad voluntaria en entidades públicas y privadas.','Voluntariado','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 003-2015-MIMP, Reglamento de la Ley General del Voluntariado.','https://www.gob.pe/mimp','voluntariado,reglamento,registro'),
('Ley N.° 29733 — Protección de datos','Artículo 5 (paráfrasis): para tratar datos personales debe obtenerse el consentimiento del titular, salvo las excepciones previstas por ley. Este consentimiento debe ser previo, informado, expreso e inequívoco cuando corresponda.','La ONG debe contar con una finalidad legítima, informar el tratamiento, obtener consentimiento cuando corresponda, proteger la información y atender los derechos de los titulares.','Protección de datos','Ana Administradora','Manos Abiertas','Ley N.° 29733, Ley de Protección de Datos Personales.','https://www.gob.pe/anpd','datos personales,privacidad,consentimiento'),
('Decreto Supremo N.° 016-2024-JUS — Reglamento de datos','Artículo 1 (paráfrasis): el Reglamento desarrolla la aplicación de la Ley N.° 29733 y regula el tratamiento de datos personales, el consentimiento, las medidas de seguridad, los derechos de los titulares, los encargados y las transferencias de información.','Desarrolla obligaciones sobre consentimiento, seguridad, encargados, transferencias, incidentes y ejercicio de derechos. Debe verificarse su vigencia y disposiciones transitorias.','Protección de datos','Ana Administradora','Manos Abiertas','Decreto Supremo N.° 016-2024-JUS, Reglamento de la Ley N.° 29733.','https://www.gob.pe/anpd','datos personales,reglamento,seguridad'),
('Decreto de Urgencia N.° 007-2020 — Marco de confianza digital','Artículo 3 (paráfrasis): el Marco de Confianza Digital busca fortalecer la seguridad, privacidad, transparencia y confianza de las personas en el entorno digital, mediante gestión de riesgos, identidad digital y atención de incidentes.','Es una referencia para la gestión de riesgos digitales, incidentes de seguridad y protección de información cuando la ONG utiliza plataformas y bases de datos.','Protección de datos','Ana Administradora','Manos Abiertas','Decreto de Urgencia N.° 007-2020, Marco de Confianza Digital.','https://www.gob.pe/pcm','seguridad digital,incidentes,información'),
('Ley N.° 30424 — Responsabilidad personas jurídicas','Artículo 3 (paráfrasis): las personas jurídicas pueden responder administrativamente cuando determinados delitos son cometidos en su nombre, por cuenta de ellas o en su beneficio directo o indirecto por personas vinculadas a la organización.','La ONG debe fortalecer integridad, controles internos, identificación de riesgos, canales de denuncia y debida diligencia para prevenir conductas ilícitas.','Gobernanza','Ana Administradora','Manos Abiertas','Ley N.° 30424, responsabilidad administrativa de las personas jurídicas.','https://www.gob.pe/institucion/minjus/normas-legales','cumplimiento,integridad,responsabilidad'),
('Decreto Legislativo N.° 1352 — Ampliación de responsabilidad','Artículo 1 (paráfrasis): se modifican disposiciones de la Ley N.° 30424 para ampliar los delitos comprendidos y fortalecer la responsabilidad de las personas jurídicas, así como la relevancia de los modelos de prevención.','Complementa la Ley N.° 30424 e impulsa la implementación de modelos de prevención y controles de cumplimiento en organizaciones.','Gobernanza','Ana Administradora','Manos Abiertas','Decreto Legislativo N.° 1352, modificación de la Ley N.° 30424.','https://www.gob.pe/institucion/minjus/normas-legales','cumplimiento,modelo de prevención,riesgos'),
('Ley N.° 29783 — Seguridad y salud laboral','Artículo 49 (paráfrasis): el empleador debe garantizar la seguridad y salud de los trabajadores, desarrollar acciones permanentes de prevención, identificar peligros, evaluar riesgos, capacitar y adoptar medidas de protección.','Cuando la ONG tiene personal o desarrolla actividades organizadas, debe evaluar riesgos, capacitar, registrar incidentes y adoptar medidas de seguridad según corresponda.','Gobernanza','Ana Administradora','Manos Abiertas','Ley N.° 29783, Ley de Seguridad y Salud en el Trabajo.','https://www.gob.pe/mtpe','seguridad,salud,prevención'),
('Ley N.° 27942 — Prevención del hostigamiento','Artículo 7 (paráfrasis): las organizaciones deben establecer medidas para prevenir y sancionar el hostigamiento sexual, capacitar a sus integrantes, contar con canales de atención y proteger a las personas denunciantes frente a represalias.','La ONG debe contar con mecanismos de prevención, orientación, atención de denuncias y protección frente a represalias, adaptados a su estructura.','Gobernanza','Ana Administradora','Manos Abiertas','Ley N.° 27942, Ley de Prevención y Sanción del Hostigamiento Sexual.','https://www.gob.pe/mtpe','hostigamiento,prevención,protección'),
('Ley N.° 29973 — Derechos y accesibilidad','Artículo 3 (paráfrasis): la persona con discapacidad tiene los mismos derechos que el resto de la población, sin discriminación y con acceso a medidas que permitan su inclusión efectiva, autonomía, accesibilidad e igualdad de oportunidades.','La ONG debe considerar accesibilidad, igualdad de oportunidades, ajustes razonables y trato digno en programas, voluntariado, empleo y atención de beneficiarios.','Gobernanza','Ana Administradora','Manos Abiertas','Ley N.° 29973, Ley General de la Persona con Discapacidad.','https://www.gob.pe/conadis','discapacidad,inclusión,accesibilidad');

insert into knowledge_items (
  title, description, content, category_id, subcategory_id, organization_id, created_by,
  author_name, legal_reference, source_url, document_type, status, visibility,
  visible_to_roles, published_at
)
select x.title, x.description, x.content, c.id, sc.id, o.id, u.id,
       x.author_name, x.legal_reference, x.source_url, 'ley', 'publicado', 'publico',
       array['administrador','creador_ong','voluntario'], now()
from legal_catalog x
join categories c on c.name='Leyes para ONG'
join subcategories sc on sc.category_id=c.id and sc.name=x.subcategory
join organizations o on o.name=x.organization
join users u on u.full_name=x.author_name;

insert into tags (name)
select distinct trim(tag_name)
from legal_catalog x
cross join lateral unnest(string_to_array(x.tags_text, ',')) as tag_name
where trim(tag_name) <> ''
on conflict (name) do nothing;

insert into item_tags (item_id, tag_id)
select k.id, t.id
from legal_catalog x
join knowledge_items k on k.title=x.title
cross join lateral unnest(string_to_array(x.tags_text, ',')) as tag_name
join tags t on t.name=trim(tag_name)
on conflict do nothing;

commit;
